### PR TITLE
Truncate long ens names so they dont interfere with icons

### PR DESCRIPTION
**Pull request by BrianS111**
Closes https://github.com/relaycc/receiver/issues/113

### CODE REVIEW

**Comment by BrianS111** [comment]
85D3F3B9-5F94-44B1-809A-80D5C3A5B04C_4_5005_c
F4A0EDE3-BE3A-4D50-B426-00E27FC851A1_4_5005_c
85996BB4-21C5-4042-BFD0-B04269891C99_4_5005_c


Here are the three scenarios (Lens, Eth, wallet) in the header with a new truncate function preventing them to overflow into the icons while still showing the last few characters

**Comment by BrianS111** [comment]
1 sec need to make a quick adjustment

**Comment by BrianS111** [comment]
Alright, now it's ready

**Review by killthebuddh4 — CHANGES_REQUESTED** [review]
* It would probably make more sense to implement a `truncateLensName` function in the `address.ts` file rather than a `truncateHeader` function that's used in one component and duplicates truncation logic from the other functions in `address.ts`. If we want to keep `truncateHeader` defined this way then it should be moved to the bottom of the `AddressInfo.tsx` file.

**Comment by BrianS111** [comment]
I made truncate header because it seems like there isn't enough space to use the functions we already have. I have the header truncating a few characters shorter than in the conversations list

**Comment by BrianS111** [comment]
Should be good now, I moved it to AddressInfo.tsx

**Pull request closed without merging**
