### PR TITLE
Removing styled components

### PR DESCRIPTION
**Pull request by BrianS111**
Closes https://github.com/relaycc/receiver/issues/30

[**Note: Pull requests which don't include the minimum details specified
in this template will probably be closed out-of-hand.**

# Issue Link or Description (the "what" and "why")

- Links to GitHub issues that this PR closes (if there's no issues to link,
  a detailed description must be included).
- The issues and description should provide a
  detailed, high-level overview of the changes included in the PR.
- Include a description of "why" the change is necessary. If it's a bug fix,
  describe the bug. If it's a refactor, describe what the refactor accomplishes.
- Please do not include implementation details in this section.

# Implementation Plan

_If the pull request is going to be a "Draft" PR for more than a day, authors
must include an implementation plan in the form of a checkpoint list._

# Implementation Details (the "how")

_A detailed description of each change in the changeset. The description should
include_

- high-level overview of the changes
- where should the reveiwer start their review, which files?
- notes on any hacky solutions that were included
- any pieces left unfinished and why

# How the changeset was tested

_A detailed list of cases which the author verified before requesting review._

- The ideal option here is a list of existing, updated, or newly-created UI
  tests that cover the included functionality.
- The next best option is probably a list of screenshots or videos.
- The fallback option is a simple-but-detailed list of steps taken to verify changes.

Changes were verified on the following platforms:

- [] Chrome desktop
- [] Firefox desktop
- [] Safari desktop
- [] Chrome Android
- [] MetaMask browser Android
- [] Safari iOS
- [] MetaMask browser iOS
](https://github.com/relaycc/receiver/issues/30)

### CODE REVIEW

**Comment by killthebuddh4** [comment]
@BrianS111 Looks good so far. Make sure to remove the `package-lock.json` file before marking the PR as ready. Also one other minor thing is that the `import 'some-file.css'` only needs to happen once per app, so it probably doesn't need to be in every single component.

**Comment by killthebuddh4** [comment]
I'm slightly surprised that it's just working with css imports, I wonder if the `postcss` plugin was previously unnecessary.

**Comment by BrianS111** [comment]
Commit / Push made with everything switched away from styled components except components involving: Exports, Props, Animations, nested selectors and svgs, which will be done in the next round.

**Comment by killthebuddh4** [comment]
> Commit / Push made with everything switched away from styled components except components involving: Exports, Props, Animations, nested selectors and svgs, which will be done in the next round.

@BrianS111 Looks good. Let me know if any of the cases you listed get weird/tricky.

**Comment by BrianS111** [comment]
Status update with recent push: No styled components are left in the project, however the dependency still remains

We should probably do this in multiple PRs if it's going to take more than a day
In terms of an implementation plan, let's do things in this order
Do a few styled-components that don't take props, check in on how it's going *Complete*
Any styled components that do not take props *Complete*
A few that do take props *Complete*
Check in here *Complete*
The rest *Complete*

The below section is ***INCOMPLETE***

Achilles will do the last few. The build config might have to happen first, I can help with this if necessary.
delete the styled-components dependency!
update the build config (how do we bundle CSS with receiver?)
update the README w/ new instructions on how to include in project

**Review by killthebuddh4 — APPROVED** [review]

**Pull request merged**
