### PR TITLE
Show lens name instead of wallet address in conversation list when th…

### PR DESCRIPTION
**Pull request by BrianS111**
Closes https://github.com/relaycc/receiver/issues/114

### CODE REVIEW

**Comment by BrianS111** [comment]
DEE4F06B-FC0B-4097-BBDB-0276265A0678_4_5005_c
Before pic

**Comment by BrianS111** [comment]
28724135-5EEC-4AB6-B454-B162A9AD325A

I have a strange feeling this PR wont get accepted.. Seems like a simple fix to make everything work. Let me know if I went in the right direction or if you'd like a different solution.

**Review by killthebuddh4 — COMMENTED** [review]
* The `peerAddressDisplay` prop is a manual override for what gets displayed so it shouldn't be removed
* The `responsiveName` and `useEnsName` hooks should be removed in favor of the `useRelayId` hook
* The logic for deciding what to show should be straightforward: "if we have an ENS name show that, if we have a Lens name, show that, otherwise show the address"

**Review by killthebuddh4 — CHANGES_REQUESTED** [review]
* The `peerAddressDisplay` prop is a manual override for what gets displayed so it shouldn't be removed
* The `responsiveName` and `useEnsName` hooks should be removed in favor of the `useRelayId` hook (We don't need to use all 3, we can just use the 1).
* The logic for deciding what to show should be straightforward: "if we have an ENS name show that, if we have a Lens name, show that, otherwise show the address"

**Comment by BrianS111** [comment]
> * The `peerAddressDisplay` prop is a manual override for what gets displayed so it shouldn't be removed
> * The `responsiveName` and `useEnsName` hooks should be removed in favor of the `useRelayId` hook (We don't need to use all 3, we can just use the 1).
> * The logic for deciding what to show should be straightforward: "if we have an ENS name show that, if we have a Lens name, show that, otherwise show the address"

useRelayId doesn't truncate anything and all 3 forms (ens, lens, address) need to be truncated 3 different ways, so I'm assuming I'll import truncateName, truncateAddress and write a new function for truncate lens and use those along with useRelayId and everything should work that way along with what you mentioned above. Does that sound about right? @killthebuddh4

**Comment by killthebuddh4** [comment]
> useRelayId doesn't truncate anything and all 3 forms (ens, lens, address) need to be truncated 3 different ways, so I'm assuming I'll import truncateName, truncateAddress and write a new function for truncate lens and use those along with useRelayId and everything should work that way along with what you mentioned above. Does that sound about right? @killthebuddh4

Yep that sounds about right.

**Comment by BrianS111** [comment]
The code has been updated @killthebuddh4 Let me know if this works. It seems to be everything we discusses. I slightly adjusted the ens function in the address.ts so when it's truncated there are 3 dots instead of 4

**Pull request closed without merging**
