### PR TITLE
Adding a link to github

### PR DESCRIPTION
**Pull request by BrianS111**
Draft PR for https://github.com/relaycc/receiver/issues/70

### CODE REVIEW

**Comment by BrianS111** [comment]
DA21D0ED-4BEF-48A1-BF54-28510D8C745F
This is what the footer looks like now per #70

**Comment by BrianS111** [comment]
Closes #70

**Comment by BrianS111** [comment]
My only thought would be that this maybe looks too much like an advertisement that companies wont wont on their page. Maybe not though... Maybe just a github logo?

**Comment by seandaopanel** [comment]
<Relay logo> Relay is open-source on <Github logo>

**Comment by BrianS111** [comment]
BD88D7F8-651E-4ED5-888D-017D3008E61F_4_5005_c

does this look right for the footer? Does anything need to be spaced / sized differently?

**Comment by BrianS111** [comment]
Maybe our logo and the GH logo should be center aligned with the text 1 sec

**Comment by BrianS111** [comment]
text is a little higher
CBD0D823-AE52-45A4-8AF3-21430E61CFF6_4_5005_c

**Comment by BrianS111** [comment]
Full context
12C1B35E-B7FB-4280-A55B-49CA26418C8D

**Comment by seandaopanel** [comment]
if the relay logo opens a new tab to try.relay.cc and the gh one opens new tab to to github.com/relaycc/receiver then lgtm

**Comment by BrianS111** [comment]
yes, they do. I'll push the code and make any adjustments needed

**Comment by BrianS111** [comment]
If there is any specific reason as to why this hasn't been merged yet that I can help out with, let me know. In my opinion the current footer is in serious need of something to be merged in it's place
21E415CD-6A6E-44EF-BD86-BF2C64C8CF6E_4_5005_c

**Review by seandaopanel — APPROVED** [review]
looks good.

**Comment by BrianS111** [comment]
@vdp @killthebuddh4

**Comment by killthebuddh4** [comment]
@BrianS111 These aren't blocking comments, but a couple notes

* Let's not inline svgs anymore, svgs can go at the bottom of the file or extracted into their own component. I'd probably default to the bottom of the file for now
* Let's not use inline styles

**Review by killthebuddh4 — APPROVED** [review]

**Pull request merged**
